hasheado_blog_homepage:
    pattern:  /
    defaults: { _controller: HasheadoBlogBundle:Default:index, page: 1 }

hasheado_blog_homepage_pagination:
    pattern:  /page/{page}
    defaults: { _controller: HasheadoBlogBundle:Default:index, page: 1 }

hasheado_blog_post_detail:
    pattern:  /{slug}
    defaults: { _controller: HasheadoBlogBundle:BlogPost:postDetail }

hasheado_blog_comment_post:
    pattern:  /comment/post
    defaults: { _controller: HasheadoBlogBundle:Default:comment }

hasheado_blog_post_by_category:
    pattern:  /category/{slug}
    defaults: { _controller: HasheadoBlogBundle:BlogCategory:byCategory }

hasheado_blog_post_archive:
    pattern:  /archive/{year}/{month}
    defaults: { _controller: HasheadoBlogBundle:Default:archive }

hasheado_blog_post_tags:
    pattern:  /tags/{slug}
    defaults: { _controller: HasheadoBlogBundle:BlogPost:byTag }

#Admin routes #####
#########################
hasheado_blog_admin_login:
    pattern:   /admin/login
    defaults:  { _controller: HasheadoBlogBundle:Admin\Security:login }
hasheado_blog_admin_login_check:
    pattern:   /admin/login_check
hasheado_blog_admin_logout:
    pattern: /admin/logout

#Dashboard
hasheado_blog_admin_dashboard:
    pattern: /admin/dashboard
    defaults: { _controller: HasheadoBlogBundle:Admin\Default:index }

#Post
hasheado_blog_admin_post_list:
    pattern: /admin/posts
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogPost:list }

hasheado_blog_admin_post_pagination:
    pattern:  /admin/posts/page/{page}
    defaults: { _controller: "HasheadoBlogBundle:Admin\BlogPost:list", page: 1 }

hasheado_blog_admin_post_filter:
    pattern:  /admin/posts/filter/{field}/{mode}
    defaults: { _controller: "HasheadoBlogBundle:Admin\BlogPost:filter" }

hasheado_blog_admin_post_add:
    pattern: /admin/post/add
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogPost:add }

hasheado_blog_admin_post_edit:
    pattern: /admin/post/{id}
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogPost:edit }

hasheado_blog_admin_post_delete:
    pattern: /admin/post/{id}/delete
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogPost:delete }

#Category
hasheado_blog_admin_category_list:
    pattern: /admin/categories
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogCategory:list }

hasheado_blog_admin_category_pagination:
    pattern:  /admin/categories/page/{page}
    defaults: { _controller: "HasheadoBlogBundle:Admin\BlogCategory:list", page: 1 }

hasheado_blog_admin_category_filter:
    pattern:  /admin/categories/filter/{field}/{mode}
    defaults: { _controller: "HasheadoBlogBundle:Admin\BlogCategory:filter" }

hasheado_blog_admin_category_add:
    pattern: /admin/category/add
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogCategory:add }

hasheado_blog_admin_category_edit:
    pattern: /admin/category/{id}
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogCategory:edit }

hasheado_blog_admin_category_delete:
    pattern: /admin/category/{id}/delete
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogCategory:delete }

#Comment
hasheado_blog_admin_comment_list:
    pattern: /admin/comments
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogComment:list }

hasheado_blog_admin_comment_pagination:
    pattern:  /admin/comments/page/{page}
    defaults: { _controller: "HasheadoBlogBundle:Admin\BlogComment:list", page: 1 }

hasheado_blog_admin_comment_filter:
    pattern:  /admin/comments/filter/{field}/{mode}
    defaults: { _controller: "HasheadoBlogBundle:Admin\BlogComment:filter" }

hasheado_blog_admin_comment_add:
    pattern: /admin/comment/add
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogComment:add }

hasheado_blog_admin_comment_edit:
    pattern: /admin/comment/{id}
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogComment:edit }

hasheado_blog_admin_comment_delete:
    pattern: /admin/comment/{id}/delete
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogComment:delete }

#Tag
hasheado_blog_admin_tag_list:
    pattern: /admin/tags
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogTag:list }

hasheado_blog_admin_tag_pagination:
    pattern:  /admin/tags/page/{page}
    defaults: { _controller: "HasheadoBlogBundle:Admin\BlogTag:list", page: 1 }

hasheado_blog_admin_tag_filter:
    pattern:  /admin/tags/filter/{field}/{mode}
    defaults: { _controller: "HasheadoBlogBundle:Admin\BlogTag:filter" }

hasheado_blog_admin_tag_add:
    pattern: /admin/tag/add
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogTag:add }

hasheado_blog_admin_tag_edit:
    pattern: /admin/tag/{id}
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogTag:edit }

hasheado_blog_admin_tag_delete:
    pattern: /admin/tag/{id}/delete
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogTag:delete }
#End Admin routes