hasheado_blog_homepage:
    pattern:  /
    defaults: { _controller: HasheadoBlogBundle:Default:index }

#Admin routes
hasheado_blog_admin_post_add:
    pattern: /admin/post/add
    defaults: { _controller: HasheadoBlogBundle:Admin:addPost }