hasheado_blog_homepage:
    pattern:  /
    defaults: { _controller: HasheadoBlogBundle:Default:index }

#Admin routes

#Post
hasheado_blog_admin_post_list:
    pattern: /admin/posts
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogPost:list }

hasheado_blog_admin_post_add:
    pattern: /admin/post/add
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogPost:add }

hasheado_blog_admin_post_edit:
    pattern: /admin/post/{id}
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogPost:edit }

hasheado_blog_admin_post_delete:
    pattern: /admin/post/{id}/delete
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogPost:delete }

#Category
hasheado_blog_admin_category_list:
    pattern: /admin/categories
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogCategory:list }

hasheado_blog_admin_category_add:
    pattern: /admin/category/add
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogCategory:add }

hasheado_blog_admin_category_edit:
    pattern: /admin/category/{id}
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogCategory:edit }

hasheado_blog_admin_category_delete:
    pattern: /admin/category/{id}/delete
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogCategory:delete }

#Comment
hasheado_blog_admin_comment_list:
    pattern: /admin/comments
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogComment:list }

hasheado_blog_admin_comment_add:
    pattern: /admin/comment/add
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogComment:add }

hasheado_blog_admin_comment_edit:
    pattern: /admin/comment/{id}
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogComment:edit }

hasheado_blog_admin_comment_delete:
    pattern: /admin/comment/{id}/delete
    defaults: { _controller: HasheadoBlogBundle:Admin\BlogComment:delete }
#End Admin routes