services:
    hasheado_blog.behaviors.listener:
        class: Hasheado\BlogBundle\EventListener\BehaviorsListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }
    hasheado_blog.entity_id.type:
        class: Hasheado\BlogBundle\Form\Type\EntityIdType
        arguments: [@doctrine]
        tags:
            - { name: form.type, alias: entity_id }
    hasheado_blog.wysiwyg.type:
        class: Hasheado\BlogBundle\Form\Type\WysiwygType
        tags:
            - { name: form.type, alias: wysiwyg }